//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientistsApp.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int RepId { get; set; }
        public string RepTheme { get; set; }
        public string RepImage { get; set; }
        public int RepAuthor { get; set; }
        public int RepConf { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        public virtual Scientists Scientists { get; set; }
    }
}
